### PR TITLE
use swc-loader instead of ts-loader

### PR DESCRIPTION
**Pull request by julianocomg**
SWC is much faster and robust than TSC. It's written in Rust and can be used with webpack by using their swc-loader.

## What was changed

Replaced ts-loader by swc-loader.

## Checklist

1. Closes 

2. How was this tested:

- We've been testing it in dev for a while by using "npm patch-package" and no errors so far.

3. Any docs updates needed?

### CODE REVIEW

**Comment by bergundy** [comment]
@julianocomg don't you need to change the webpack config too?

**Comment by julianocomg** [comment]
> @julianocomg don't you need to change the webpack config too?

I don't think so. These files were the only place were ts-loader was mentioned.

**Comment by julianocomg** [comment]
> @julianocomg don't you need to change the webpack config too?

Yeah, my bad. I forgot to push the webpack config change. Fixed now.

**Review by bergundy — APPROVED** [review]

**Comment by bergundy** [comment]
Thanks!

Out of curiosity, how much does it actually improve build times?

**Comment by julianocomg** [comment]
> Thanks!
> 
> Out of curiosity, how much does it actually improve build times?

Our workers were taking ~1.5 min to compile on our dev's machine. It now takes 5 seconds (not kidding).

**Comment by julianocomg** [comment]
Just added the missing @swc/core dependency. swc-loader needs it to work.

**Comment by julianocomg** [comment]
@bergundy Does the CI for the last commit need to be triggered again?

**Comment by bergundy** [comment]
@julianocomg I just triggered it

**Comment by julianocomg** [comment]
> @julianocomg I just triggered it

Seems that the last 2 CIs are stuck :(

**Comment by lorensr** [comment]
> Our workers were taking ~1.5 min to compile on our dev's machine. It now takes 5 seconds (not kidding).

Wow, thanks! 😄

> Seems that the last 2 CIs are stuck :(

image

Yeah that's a long test! 😆 Since it's in progress, I can't manually re-run them. Try merging with latest `main`? Also, I recommend setting this in future: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

**Comment by julianocomg** [comment]
@lorensr Unfortunately that option is not appearing to me for this existing PR, but I merged main, let's see what happens. The "sdk-features-test" job seems to be failing but I don't think the error is related to my change 🤔

**Comment by julianocomg** [comment]
@lorensr oh... now seems that a lot of things are failing after that merge

**Comment by lorensr** [comment]
Sorry about that! For now, I figured out how to manually restart. I'll work on fixing the sdk-features action soon, and the windows built-and-test is intermittent—haven't looked into that one yet, tracking here: https://github.com/temporalio/sdk-typescript/issues/496#issuecomment-1049030111

**Comment by lorensr** [comment]
Okay the window build-and-test failure is much less intermittent than it used to be! I'll look into it tomorrow.

**Comment by lorensr** [comment]
Fixed test in #526. Merged w/ latest main locally and tests pass. 
image

**Comment by julianocomg** [comment]
@lorensr that's awesome! thanks dude!! 🥳

**Comment by lorensr** [comment]
Thank *you*! ☺️

**Pull request merged**
