### PR TITLE
chore(core): Update sdk-core

### PR DESCRIPTION
**Pull request by mjameswh**
Update SDK Core, in preparation for release 1.6.0

### CODE REVIEW

**Review by bergundy — APPROVED** [review]
Much diff

**Comment by Sushisource** [comment]
I have some important fixes I want to merge today - let's make sure to get those in first.

https://github.com/temporalio/sdk-core/pull/475

and https://github.com/temporalio/sdk-core/pull/478

**Comment by bergundy** [comment]
@Sushisource we can wait with the release for tomorrow morning but I'd rather not delay this further.

**Comment by bergundy** [comment]
And patch releases are easy to make if we don't want to wait.

**Comment by Sushisource** [comment]
> @Sushisource we can wait with the release for tomorrow morning but I'd rather not delay this further.

I mean, these literally need to just get approved and merged, it's a matter of a few minutes.

**Pull request merged**
