### PR TITLE
chore(infra): switch to yarn workspaces

### PR DESCRIPTION
**Pull request by StevenLangbroek**
BREAKING CHANGE:
it's hard to predict but personally I prefer to mark such fundamental
changes as breaking, as it might surprise devs and lead to unnecessary
questions / bug reports.

## What was changed

@bergundy mentioned that in retrospect he'd have rather gone with Workspaces than with `lerna`. This PR switches from `npm` to `yarn`, enables Workspaces and configures `lerna` appropriately.

## Why?

Lerna can be a real PITA.

## Checklist

- [ ] Discuss publication process
- [ ] Update contribution guides
- [ ] Test out all `scripts`

### CODE REVIEW

**Comment by bergundy** [comment]
Thanks @StevenLangbroek!

There's more work to be done before we can switch like fix all of our CI scripts.
TBH, I'm not sure how much we actually gain from this change now that I see it.
Looks like lerna is still the main driver for the dev flow and is required for versioning and publishing.

**Comment by StevenLangbroek** [comment]
Hey @bergundy! That's right, I'm not done ;). I'd like to add `turborepo` as a runner, but wanted to ask how you prefer publication & versioning to work... Are you happy with the current, conventional-commits based approach?

**Comment by StevenLangbroek** [comment]
I can automate [this entire process](https://github.com/temporalio/sdk-typescript/blob/main/CONTRIBUTING.md#publishing) with really no effort at all...

**Comment by bergundy** [comment]
> Hey @bergundy! That's right, I'm not done ;). I'd like to add `turborepo` as a runner, but wanted to ask how you prefer publication & versioning to work... Are you happy with the current, conventional-commits based approach?

I'd be onboard if we want to replace lerna with turbo.
We're pretty happy with the current, conventional-commits approach but we still have to manually edit the CHANGELOG after collecting the commits, we use `git-cliff` right now. I'm open to suggestions here too.

**Comment by bergundy** [comment]
> I can automate [this entire process](https://github.com/temporalio/sdk-typescript/blob/main/CONTRIBUTING.md#publishing) with really no effort at all...

I started working on that a [while back](https://github.com/temporalio/sdk-typescript/pull/395) but dropped it because we had more pressing issues to address.
Automating it with scripts isn't that big of an issue, testing the whole CI flow just takes time as CI typically does and it gets worse with our weak GH runners.

**Comment by StevenLangbroek** [comment]
Alright. And you prefer for packages to be versioned together or independently?

**Comment by bergundy** [comment]
> Alright. And you prefer for packages to be versioned together or independently?

Missed this comment.

Together would be preferable, for some reason lerna doesn't do that.

**Comment by lorensr** [comment]
Very pro turborepo. Also, new note at top of Lerna readme 😄

image

**Comment by bergundy** [comment]
Oh.. that's news, yes, so lets switch to turborepo.
It's not urgent by any means but would be nice to get done.

**Comment by lorensr** [comment]
For reference, turborepo/workspaces/changesets: https://twitter.com/rwieruch/status/1531666889340076037?s=21&t=3ROWIFDmeWqCi3xZ2gq1hg

**Comment by bergundy** [comment]
Closing this for now, we'll probably change the tooling at some point soon

**Pull request closed without merging**
