### PR TITLE
fix(workflow): Fail workflow task instead of run on workflow not found

### PR DESCRIPTION
**Pull request by bergundy**

### CODE REVIEW

**Review by lorensr — APPROVED** [review]
Taking this off my todo list, thanks! Whether missing Activities should fail WE or Task is still on it

**Comment by bergundy** [comment]
@lorensr Not sure what you mean by activity not found failing workflow task

**Comment by lorensr** [comment]
Ah, think it should be "what happens when Worker is missing an Activity, and does that match other SDKs"

**Comment by bergundy** [comment]
@lorensr it was already fixed, we return a `non non retryable application failure` :)

**Pull request merged**
