### PR TITLE
fix(bundler): avoid 'package source-map-loader not found' in PNPM

### PR DESCRIPTION
**Pull request by mjameswh**
## What was changed
In webpack configuration, replaced `'source-map-loader'` by `require.resolve('source-map-loader')`

## Why?
Plugins dependencies have to be resolved in the context of the `@temporalio/worker` package. This is true in general, but essential with strict package managers (including PNPM and Yarn3).

**Note: NOT TESTED**

### CODE REVIEW

**Review by bergundy — APPROVED** [review]
Thanks! That makes a lot of sense

**Comment by mjameswh** [comment]
I just pushed a second (unrelated) change to this branch. Trying to fix some CI build issues that makes it error when processing PR from third party commiters (like me)...

**Comment by lorensr** [comment]
Algolia thing is now fixed in main

**Comment by bergundy** [comment]
Thanks @mjameswh

**Pull request merged**
