### PR TITLE
chore: Upgrade interceptors-opentelemetry opentelemetry deps

### PR DESCRIPTION
**Pull request by maxgurewitz**
## What was changed
I've upgraded the interceptors-opentelemetry opentelemetry dependencies.

## Why?

Unfortunately the opentelemetry team inadvertently introduce a backwards incompatible change with a minor version change in the resources package. 

https://github.com/open-telemetry/opentelemetry-js/pull/3677

This backwards incompatible change in combination with the lib's use of older versions of `@opentelemetry/resources` is preventing me from using this package. 

## Checklist

I could use some assistance / guidance in testing these changes.

### CODE REVIEW

**Review by bergundy — APPROVED** [review]
We'd need to update package-lock.json but otherwise LGTM.
Thanks!

**Comment by maxgurewitz** [comment]
@bergundy done!

**Comment by bergundy** [comment]
We already have automated tests, that should cover it.
I regenerated package-lock.json and fixed the compilation errors.
For some reason I can't push my changes though, not sure if it's me or you need to give permissions to push into your branch.

**Comment by bergundy** [comment]
You should have this checked:

image

Anyways, I created a PR into your branch, please accept it and I'll merge this PR in turn

https://github.com/dittofeed/sdk-typescript/pull/1.

**Comment by maxgurewitz** [comment]
Merged!

**Comment by bergundy** [comment]
Opened an alternative PR here: https://github.com/temporalio/sdk-typescript/pull/1107.

Thanks @maxgurewitz

**Pull request closed without merging**
